---
# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: link the bash profile configuration
  file:
    dest: "{{ ansible_user_dir }}/.bash_profile"
    src: "{{ playbook_dir }}/roles/bash/files/bash_profile"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: link the bash functions
  file:
    dest: "{{ ansible_user_dir }}/.bash_functions"
    src: "{{ playbook_dir }}/roles/bash/files/bash_functions"
    state: link

- name: install bashrc
  template:
    dest: "{{ ansible_user_dir }}/.bashrc"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0600
    src: bashrc.j2
