---
- name: Create bash directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.bash"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: "0755"
    state: directory

- name: Download bash-it
  ansible.builtin.git:
    dest: "{{ ansible_user_dir }}/.bash/bash-it"
    repo: https://github.com/Bash-it/bash-it.git
    version: v3.0.3

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Link the bash profile configuration
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.bash_profile"
    src: "{{ playbook_dir }}/roles/bash/files/bash_profile"
    state: link
    force: true

- name: Install bashrc
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.bashrc"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: "0600"
    src: bashrc.j2

- name: Cleanup old bash_functions
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_user_dir }}/.bash/bash_functions"
    - "{{ ansible_user_dir }}/.bash_functions"
