---
- name: Creating bash configuration directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.bash"
    state: directory

- name: Installing bash-it
  ansible.builtin.git:
    dest: "{{ ansible_user_dir }}/.bash/bash-it"
    repo: https://github.com/Bash-it/bash-it.git
    version: v3.0.3

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking `.bash_profile`
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.bash_profile"
    force: true
    src: "{{ playbook_dir }}/roles/bash/files/bash_profile"
    state: link

- name: Copying `.bashrc`
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.bashrc"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: bashrc.j2
