---
- hosts: localhost
  roles:
    - { role: bash, when: "mtype == 'personal'"  }
    - { role: git, when: "mtype == 'personal' or mtype == 'work'" }
    - { role: gnupg, when: "mtype == 'personal' or mtype == 'work'" }
    - { role: ruby, when: "mtype == 'personal'" }
    - { role: ssh, when: "mtype == 'personal' or mtype == 'work'" }
    - { role: urlwatch, when: "mtype == 'personal' or mtype == 'work'" }
    - { role: vim, when: "mtype == 'personal' or mtype == 'work'" }
    - { role: vpn, when: "mtype == 'personal'" }
    - { role: xorg, when: "mtype == 'personal'" }
    - { role: zsh, when: "mtype == 'personal'" }
