---
- hosts: localhost
  roles:
    - {role: arch, when: "mtype == 'personal'"}
    - {role: aws, when: "mtype == 'personal'"}
    - {role: bash, when: "mtype == 'personal'"}
    - {role: git, when: "mtype == 'personal' or mtype == 'work'"}
    - {role: gnupg, when: "mtype == 'personal' or mtype == 'work'"}
    - {role: hexchat, when: "mtype == 'personal' and ansible_os_family != 'Darwin'"}
    - {role: macos, when: "ansible_os_family == 'Darwin'"}
    - {role: ruby, when: "mtype == 'personal'"}
    - {role: ssh, when: "mtype == 'personal' or mtype == 'work'"}
    - {role: tmux, when: "mtype == 'personal' or mtype == 'work'"}
    - {role: urlwatch, when: "mtype == 'personal' or mtype == 'work'"}
    - {role: vim, when: "mtype == 'personal' or mtype == 'work'"}
    - {role: vpn, when: "mtype == 'personal'"}
    - {role: xorg, when: "mtype == 'personal'"}
    - {role: zsh, when: "mtype == 'personal' or mtype == 'work'"}
