---
- name: Setup dotfiles
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
    - role: arch
      when: ansible_os_family == 'Archlinux'
    - role: asdf
      when: mtype == 'work' and wedition == 'facile'
    - role: aws
      when: mtype == 'personal' and wedition != 'media'
    - role: bash
      when: mtype == 'personal' or mtype == 'server'
    - role: git
    - role: gnupg
      when: mtype != 'server'
    - role: gnome
      when:
        - ansible_os_family == 'Archlinux'
        - mtype == 'personal' or mtype == 'work'
        - wedition != 'media' # xfce
    - role: hexchat
      when:
        - ansible_os_family != 'Darwin'
        - mtype == 'personal' and wedition != 'media'
    - role: macos
      when: ansible_os_family == 'Darwin'
    - role: oci
      when: mtype == 'personal' and wedition != 'media'
    - role: other
    - role: ruby
      when: mtype == 'personal' and wedition != 'media'
    - role: screen
      when: mtype == 'server'
    - role: ssh
    - role: terraform
      when: mtype == 'personal' and wedition != 'media'
    - role: tmux
      when: mtype != 'server'
    - role: urlwatch
    - role: vim
    - role: vpn
      when: mtype == 'personal'
    - role: xorg
      when:
        - ansible_os_family != 'Darwin'
        - mtype != 'server'
        - wedition != 'media'
    - role: zsh
      when:
        - mtype != 'server'
        - wedition != 'media'

# vim: ft=yaml.ansible
