---
- hosts: localhost
  roles:
    - role: arch
      when: ansible_os_family == 'Archlinux' and mtype == 'personal'
    - role: aws
      when: mtype == 'personal'
    - role: bash
      when: mtype == 'personal'
    - role: git
    - role: gnupg
    - role: hexchat
      when: ansible_os_family != 'Darwin' and mtype == 'personal'
    - role: macos
      when: ansible_os_family == 'Darwin'
    - role: ruby
      when: mtype == 'personal'
    - role: ssh
    - role: terraform
      when: mtype == 'personal'
    - role: tmux
    - role: urlwatch
    - role: vim
    - role: vpn
      when: mtype == 'personal'
    - role: xorg
      when: ansible_os_family != 'Darwin'
    - role: zsh

# vim: ft=yaml.ansible
