#!/bin/bash -e

SSH_REPO="git@github.com:mfinelli/dotfiles.git"
HTTPS_REPO="https://github.com/mfinelli/dotfiles.git"

if ! command -v git > /dev/null 2>&1; then
    echo >&2 "Git not found, aborting!"
    exit 1
fi

cd ~
git clone "$HTTPS_REPO" .dotfiles
cd .dotfiles
git remote rm origin
git remote add origin "$SSH_REPO"

exit 0
