#!/bin/bash

# Since we need to ask the git user name and email we'll generate the entire
# git config on the fly.
function setup_git() {
    echo -n "What is your git name? "
    read git_user
    git config --global user.name "$git_user"
    echo -n "What is your git email? "
    read git_email
    git config --global user.email "$git_email"

    # Aliases
    net_a="log --color --graph --pretty=format:'%Cred%h%Creset"
    net_a="$net_a -%C(yellow)%d%Creset %s"
    net_a="$net_a %Cgreen(%cr)%C(bold blue)<%an>%Creset' --abbrev-commit"
    git config --global alias.network "$net_a"
}

function desktop_install() {
    setup_git
}

function server_install() {
    echo ""
}

echo "Welcome to the Dotfiles install!"
echo -n "Which environment would you like to setup? "

read install_environment

case "$install_environment" in
    'desktop')
        desktop_install
        ;;
    'server')
        server_install
        ;;
    *)
        echo "Not a valid environment. Please enter desktop or server."
        ;;
esac
