#!/bin/bash

cd ~/

rm .bashrc
rm .bash_functions
rm .vimrc
rm .mutt
rm .muttrc
rm .gitconfig
rm .mbsyncrc
rm .msmtprc
rm .gnupg/gpg.conf
rm -rf .vim
rm -rf .mail
rm .zshrc
rm .Xresources
rm .tmux.conf
rm -rf .ssh
rm .vpn
