#!/bin/bash -e

# if no arguments then return the vault secret
# else encrypt a new secret

if [[ $# -eq 0 ]]; then
  if [[ ! -f vault.asc ]]; then
    echo >&2 "error: unable to find vault.asc!"
    exit 1
  fi

  gpg --batch --quiet --decrypt vault.asc
  exit 0
fi

if [[ $1 == -v || $1 == --view ]]; then
  if [[ $# -eq 2 && -f $2 ]]; then
    ansible-vault view --vault-password-file ./vault "$2"
  else
    echo "TODO string view"
  fi
else
  if [[ $# -eq 1 && -f $1 ]]; then
    ansible-vault encrypt --vault-password-file ./vault "$1"
  elif [[ $# -eq 2 ]]; then
    echo "encrypt string $2 as key $1"
  else
    echo >&2 "usage: $(basename "$0") [-v|--view] ./path/to/file OR key value"
  fi
fi

exit 0
