---
- name: Creating irssi directories
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_user_dir }}/.config/irssi"
    - "{{ ansible_user_dir }}/.config/irssi/certs"
    - "{{ irssi_homedir }}"
    - "{{ irssi_homedir }}/scripts"
    - "{{ irssi_homedir }}/scripts/autorun"

- name: Installing irssi scripts
  ansible.builtin.git:
    dest: "{{ irssi_homedir }}/scripts.irssi.org"
    repo: https://github.com/irssi/scripts.irssi.org.git
    version: HEAD

- name: Installing weed theme
  ansible.builtin.git:
    dest: "{{ irssi_homedir }}/weed"
    repo: https://github.com/ronilaukkarinen/weed.git
    version: HEAD

- name: Linking upstream scripts
  ansible.builtin.file:
    dest: "{{ irssi_homedir }}/scripts/{{ item }}"
    src: "{{ irssi_homedir }}/scripts.irssi.org/scripts/{{ item }}"
    state: link
  loop:
    - adv_windowlist.pl
    - awaybar.pl
    - nickcolor.pl
    - nicklist.pl
    - trackbar.pl
    - usercount.pl

- name: Linking autorun scripts
  ansible.builtin.file:
    dest: "{{ irssi_homedir }}/scripts/autorun/{{ item }}"
    src: "{{ irssi_homedir }}/scripts/{{ item }}"
    state: link
  loop:
    - trackbar.pl

- name: Copying authentication certificates
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/irssi/certs/{{ item }}.pem"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: "{{ item }}.pem"
  loop:
    - supermario

- name: Linking weed theme
  ansible.builtin.file:
    dest: "{{ irssi_homedir }}/weed.theme"
    src: "{{ irssi_homedir }}/weed/weed.theme"
    state: link

- name: Copying irssi configuration
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.config/irssi/config"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: config.j2
