---
- name: Creating irssi directories
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_user_dir }}/.config/irssi"
    - "{{ ansible_user_dir }}/.config/irssi/certs"
    - "{{ ansible_user_dir }}/.local/share/irssi"

- name: Copying authentication certificates
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/irssi/certs/{{ item }}.pem"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: "{{ item }}.pem"
  loop:
    - supermario

- name: Copying irssi configuration
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.config/irssi/config"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: config.j2
