---
- name: Creating OCI configuration directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.oci"
    state: directory

- name: Copying OCI private key
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.oci/oci.pem"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: oci.pem

- name: Copying OCI configuration
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.oci/config"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: config.j2
