---
# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking `.Xresources`
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.Xresources"
    src: "{{ playbook_dir }}/roles/xorg/files/Xresources"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking XDG user directories configuration
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/user-dirs.dirs"
    force: true
    src: "{{ playbook_dir }}/roles/xorg/files/user-dirs.dirs"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking XDG user directories locale configuration
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/user-dirs.locale"
    force: true
    src: "{{ playbook_dir }}/roles/xorg/files/user-dirs.locale"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking keymapper configuration
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/keymapper.conf"
    src: "{{ playbook_dir }}/roles/xorg/files/keymapper.conf"
    state: link
