---
# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Link the xresources config in place
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.Xresources"
    src: "{{ playbook_dir }}/roles/xorg/files/Xresources"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Link the user dirs config in place
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/user-dirs.dirs"
    force: true
    src: "{{ playbook_dir }}/roles/xorg/files/user-dirs.dirs"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Link the user dirs locale config in place
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/user-dirs.locale"
    force: true
    src: "{{ playbook_dir }}/roles/xorg/files/user-dirs.locale"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Link the keymapper config in place
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/keymapper.conf"
    src: "{{ playbook_dir }}/roles/xorg/files/keymapper.conf"
    state: link

# TODO: convert into dconf community module
# - name: ensure bluetooth download directory is correct
#   when: mtype != 'server'
#   gsetting:
#     key: org.blueman.transfer.shared-path
#     value: "'{{ ansible_user_dir }}/Downloads'"
