---
- name: Creating autostart directory
  when: ansible_os_family != 'Darwin'
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.config/autostart"
    state: directory

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking keymapper configuration
  when: ansible_os_family != 'Darwin'
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/keymapper.conf"
    src: "{{ playbook_dir }}/roles/other/files/keymapper.conf"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking keymapper autostart override (--no-tray)
  when: ansible_os_family != 'Darwin'
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/autostart/keymapper.desktop"
    src: "{{ playbook_dir }}/roles/other/files/keymapper.desktop"
    state: link

- name: Creating RaspberryPi Imager configuration directory
  when: ansible_os_family != 'Darwin'
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.config/Raspberry Pi"
    state: directory

- name: Copying RaspberryPi Imager configuration
  when: ansible_os_family != 'Darwin'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/Raspberry Pi/Imager.conf"
    group: "{{ whoami_group }}"
    mode: "0644"
    owner: "{{ whoami }}"
    src: imager.conf

- name: Creating libvirt machine images directory
  when: ansible_os_family == 'Archlinux' and mtype != 'server'
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.local/{{ item }}"
    state: directory
  loop:
    - var
    - var/libvirt

- name: Creating bin directory in $HOME
  when: mtype != 'server'
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/bin"
    state: directory

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Copying pocket portal submit script
  when: mtype != 'server'
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/bin/ppq"
    src: "{{ playbook_dir }}/roles/other/files/ppqsubmit.py"
    state: link

- name: Creating tailscale tray startup
  when: mtype == 'personal' and ansible_system == "Linux"
  ansible.builtin.command:
    cmd: tailscale configure systray --enable-startup=systemd
    creates: >-
      {{ ansible_user_dir }}/.config/systemd/user/tailscale-systray.service
  register: other_tailscale_systray

- name: Enabling tailscale tray
  when: mtype == 'personal' and ansible_system == "Linux"
  ansible.builtin.systemd:
    daemon_reload: "{{ other_tailscale_systray.changed | bool }}"
    enabled: true
    name: tailscale-systray.service
    scope: user
