---
# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking keymapper configuration
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/keymapper.conf"
    src: "{{ playbook_dir }}/roles/other/files/keymapper.conf"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking keymapper autostart override (--no-tray)
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/autostart/keymapper.desktop"
    src: "{{ playbook_dir }}/roles/other/files/keymapper.desktop"
    state: link

- name: Copying `.backuprc`
  when:
    - ansible_os_family != 'Darwin'
    - mtype != 'server' or wedition == 'personal'
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.backuprc"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: backuprc.j2

- name: Creating RaspberryPi Imager configuration directory
  when: ansible_os_family != 'Darwin'
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.config/Raspberry Pi"
    state: directory

- name: Copying RaspberryPi Imager configuration
  when: ansible_os_family != 'Darwin'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/Raspberry Pi/Imager.conf"
    group: "{{ whoami_group }}"
    mode: "0644"
    owner: "{{ whoami }}"
    src: imager.conf

- name: Creating libvirt machine images directory
  when: ansible_os_family == 'Archlinux' and mtype != 'server'
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.local/{{ item }}"
    state: directory
  loop:
    - var
    - var/libvirt
