---
- name: Creating GnuPG configuration directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0700"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.gnupg"
    state: directory

- name: Copying GnuPG configuration
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gnupg/gpg.conf"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: gpg.conf.j2

- name: Copying GnuPG Dirmngr configuration
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gnupg/dirmngr.conf"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: dirmngr.conf.j2

- name: Linking GnuPG agent configuration
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gnupg/gpg-agent.conf"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: gpg-agent.conf.j2
