---
- name: ensure gnupg directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.gnupg"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0700
    state: directory

- name: install gnupg gpg.conf
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gnupg/gpg.conf"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0600
    src: gpg.conf.j2

- name: install dirmngr config
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gnupg/dirmngr.conf"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0600
    src: dirmngr.conf.j2

- name: link gpg-agent config
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gnupg/gpg-agent.conf"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0600
    src: gpg-agent.conf.j2
