---
- name: Ensure gnupg directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0700"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.gnupg"
    state: directory

- name: Install gnupg gpg.conf
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gnupg/gpg.conf"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: gpg.conf.j2

- name: Install dirmngr config
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gnupg/dirmngr.conf"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: dirmngr.conf.j2

- name: Link gpg-agent config
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gnupg/gpg-agent.conf"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: gpg-agent.conf.j2
