---
# Settings -> Desktop & Screen Saver -> Screen Saver -> Show screen saver after
- name: Setting screen saveer to start after 20 minutes idle
  community.general.osx_defaults:
    domain: com.apple.screensaver
    host: currentHost
    key: idleTime
    type: int
    value: 1200

# Settings -> Desktop & Screen Saver -> Screen Saver -> Show with clock
- name: Enabling clock on screen saver
  community.general.osx_defaults:
    domain: com.apple.screensaver
    host: currentHost
    key: showClock
    type: bool
    value: true
