---
# Settings -> Dock & Menu Bar -> Dock & Menu Bar ->
# Automatically hide and show the Dock
- name: Enabling dock autohide
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true

# Settings -> Dock & Menu Bar -> Bluetooth -> Show in Menu Bar
- name: Enabling showing bluetooth in menu bar
  community.general.osx_defaults:
    domain: com.apple.controlcenter
    host: currentHost
    key: Bluetooth
    type: int
    value: 2 # 8 is off

# Settings -> Dock & Menu Bar -> Sound -> Show in Menu Bar (always)
- name: Enabling always show sound in the menu bar
  when: islaptop == 'true'
  community.general.osx_defaults:
    domain: com.apple.controlcenter
    host: currentHost
    key: Sound
    type: int
    value: 18 # 8 is off; 2 is when active

# Settings -> Dock & Menu Bar -> Battery -> *
- name: Configuring battery settings for menu bar
  when: islaptop == 'true'
  community.general.osx_defaults:
    domain: com.apple.controlcenter
    host: currentHost
    key: Battery
    type: int
    value:
      19 # 24 is off; 18 is show in menu bar only;
      # 25 is show in control center only

# Settings -> Dock & Menu Bar -> Battery -> Show percentage
- name: Enabling battery percentage in the menu bar
  when: islaptop == 'true'
  community.general.osx_defaults:
    domain: com.apple.controlcenter
    host: currentHost
    key: BatteryShowPercentage
    type: bool
    value: true

# Settings -> Dock & Menu Bar -> Clock -> *
- name: Configuring menu bar clock format
  community.general.osx_defaults:
    domain: com.apple.menuextra.clock
    key: DateFormat
    type: string
    value: EEE MMM d  H:mm:ss
