---
# Settings -> General -> Appearance
- name: Enable automatic light/dark mode
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleInterfaceStyleSwitchesAutomatically
    type: bool
    value: true
