---
# Settings -> General -> Appearance
- name: set light/dark mode automatically
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleInterfaceStyleSwitchesAutomatically
    type: bool
    value: true
