---
- name: Set general settings
  ansible.builtin.import_tasks: general.yml

- name: Set desktop settings
  ansible.builtin.import_tasks: desktop.yml

- name: Set dock and menu bar settings
  ansible.builtin.import_tasks: dock.yml

- name: Set finder settings
  ansible.builtin.import_tasks: finder.yml

- name: Set mission control settings
  ansible.builtin.import_tasks: missioncontrol.yml

- name: Configure iTerm2
  ansible.builtin.import_tasks: iterm.yml

# Settings -> Trackpad -> Scroll & Zoom -> Scroll Direction: natural
- name: Don't use "natural scrolling"
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: false

# Settings -> Security & Privacy -> Privacy -> Apple Advertising ->
# Personalized Ads
- name: Turn off personalized ads
  community.general.osx_defaults:
    domain: com.apple.AdLib
    key: allowApplePersonalizedAdvertising
    type: bool
    value: false

# I'm not sure where in the GUI this lives
- name: Turn on force limit add tracking
  community.general.osx_defaults:
    domain: com.apple.AdLib
    key: forceLimitAdTracking
    type: bool
    value: true

# Settings -> Language & Region -> Time format
- name: Set time format to 24 hour
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleICUForce24HourTime
    type: bool
    value: true

# I don't think it's possible to set this via GUI
# https://apple.stackexchange.com/a/296000
- name: Don't write .DS_Store files to USB drives or network shares
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: "{{ item }}"
    type: bool
    value: true
  loop:
    - DSDontWriteNetworkStores
    - DSDontWriteUSBStores
