---
- name: Ensure .ssh directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0700"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory

- name: Write out public keys
  when: mtype == 'personal' and wedition != 'media'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ item }}.pub"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: keys/{{ item }}.pub
  loop: "{{ ssh_keys }}"

- name: Write out private keys
  when: mtype == 'personal' and wedition != 'media'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ item }}"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: keys/{{ item }}
  loop: "{{ ssh_keys }}"

- name: Write out public key
  when: mtype == 'personal' and wedition == 'media'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: keys/emerald.pub

- name: Write out private key
  when: mtype == 'personal' and wedition == 'media'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/id_rsa"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: keys/emerald

- name: Write out public key
  when: mtype == 'work'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: keys/work.pub

- name: Write out private key
  when: mtype == 'work'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/id_rsa"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: keys/work

# https://serverfault.com/a/599565
- name: Write out ssh pub keys for forwarding
  when: mtype == 'server' and wedition == 'personal'
  ansible.builtin.shell:
    cmd: >
      set -e -o pipefail;
      ssh-add -L | grep '!{{ item }}$'
      > {{ ansible_user_dir }}/.ssh/{{ item }}.pub
    creates: "{{ ansible_user_dir }}/.ssh/{{ item }}.pub"
  loop:
    - arch
    - github

- name: Install ssh config
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.ssh/config"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: config.j2
