---
- name: Creating SSH configuration directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0700"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory

- name: Copying non-media public keys (at home)
  when: mtype == 'personal' and wedition != 'media'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ item }}.pub"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: keys/{{ item }}.pub
  loop: "{{ ssh_keys }}"

- name: Copying non-media private keys (at home)
  when: mtype == 'personal' and wedition != 'media'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ item }}"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: keys/{{ item }}
  loop: "{{ ssh_keys }}"

- name: Copying media public keys (at home)
  when: mtype == 'personal' and wedition == 'media'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: keys/emerald.pub

- name: Copying media private keys (at home)
  when: mtype == 'personal' and wedition == 'media'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/id_rsa"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: keys/emerald

- name: Copying public key (at work)
  when: mtype == 'work'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: keys/work.pub

- name: Copying private key (at work)
  when: mtype == 'work'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/id_rsa"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: keys/work

# https://serverfault.com/a/599565
- name: Writing out SSH public keys for forwarding
  when: mtype == 'server' and wedition == 'personal'
  ansible.builtin.shell:
    cmd: >
      set -e -o pipefail;
      ssh-add -L | grep '!{{ item }}$'
      > {{ ansible_user_dir }}/.ssh/{{ item }}.pub &&
      chmod 0600 {{ ansible_user_dir }}/.ssh/{{ item }}.pub
    creates: "{{ ansible_user_dir }}/.ssh/{{ item }}.pub"
  args:
    executable: /bin/bash
  loop:
    - arch
    - github

- name: Copying SSH configuration
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.ssh/config"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: config.j2
