# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

right_format="$aws"

[directory]
fish_style_pwd_dir_length = 1

[aws]
symbol = ' '
