---
- name: ensure .asdf directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0755
    state: directory
  loop:
    - .asdf
    - .asdf/plugins

- name: install asdf plugins
  ansible.builtin.git:
    dest: "{{ ansible_user_dir }}/.asdf/plugins/{{ item.name }}"
    repo: "{{ item.repo }}"
    version: HEAD
  loop: "{{ asdf_plugins }}"
