---
# on archlinux install the ttf-meslo-nerd-font-powerlevel10k package
# https://aur.archlinux.org/packages/ttf-meslo-nerd-font-powerlevel10k/
# and the nerd-fonts-jetbrains-mono package
# https://aur.archlinux.org/packages/nerd-fonts-jetbrains-mono/

- name: Download meslo nerd font
  when: ansible_os_family == "Darwin"
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/{{ item | urlencode }}.ttf
    dest: "{{ ansible_user_dir }}/Library/Fonts/{{ item }}.ttf"
    mode: "0664"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
  loop:
    - MesloLGS NF Regular
    - MesloLGS NF Bold
    - MesloLGS NF Italic
    - MesloLGS NF Bold Italic

- name: Ensure local fonts directory
  when: ansible_os_family == "Debian"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share/fonts"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: "0755"
    state: directory

- name: Ensure directory for nerd fonts
  when: ansible_os_family == "Debian"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share/fonts/Bitstream/TrueType/{{ item }}"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: "0755"
    state: directory
  loop:
    - MesloLGS NF
    - JetBrains Mono NF

- name: Download meslo nerd font
  when: ansible_os_family == "Debian"
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/{{ item | urlencode }}.ttf
    dest: "{{ ansible_user_dir }}/.local/share/fonts/Bitstream/TrueType/MesloLGS NF/{{ item | replace(' ', '_') }}.ttf"
    mode: "0644"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
  loop:
    - MesloLGS NF Regular
    - MesloLGS NF Bold
    - MesloLGS NF Italic
    - MesloLGS NF Bold Italic
  notify:
    - Rebuild local font cache

- name: Download jetbrains nerd font
  when: ansible_os_family == "Debian"
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/NoLigatures/{{ item.kind }}/complete/{{ item.font | urlencode }}.ttf
    dest: "{{ ansible_user_dir }}/.local/share/fonts/Bitstream/TrueType/JetBrains Mono NF/{{ item.font | replace(' ', '_') }}.ttf"
    mode: "0644"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
  loop:
    - kind: Bold
      font: JetBrains Mono NL Bold Nerd Font Complete Mono
    - kind: BoldItalic
      font: JetBrains Mono NL Bold Italic Nerd Font Complete Mono
    - kind: ExtraBold
      font: JetBrains Mono NL ExtraBold Nerd Font Complete Mono
    - kind: ExtraBoldItalic
      font: JetBrains Mono NL ExtraBold Italic Nerd Font Complete Mono
    - kind: ExtraLight
      font: JetBrains Mono NL ExtraLight Nerd Font Complete Mono
    - kind: ExtraLightItalic
      font: JetBrains Mono NL ExtraLight Italic Nerd Font Complete Mono
    - kind: Italic
      font: JetBrains Mono NL Italic Nerd Font Complete Mono
    - kind: Light
      font: JetBrains Mono NL Light Nerd Font Complete Mono
    - kind: LightItalic
      font: JetBrains Mono NL Light Italic Nerd Font Complete Mono
    - kind: Medium
      font: JetBrains Mono NL Medium Nerd Font Complete Mono
    - kind: MediumItalic
      font: JetBrains Mono NL Medium Italic Nerd Font Complete Mono
    - kind: Regular
      font: JetBrains Mono NL Regular Nerd Font Complete Mono
    - kind: SemiBold
      font: JetBrains Mono NL SemiBold Nerd Font Complete Mono
    - kind: SemiBoldItalic
      font: JetBrains Mono NL SemiBold Italic Nerd Font Complete Mono
    - kind: Thin
      font: JetBrains Mono NL Thin Nerd Font Complete Mono
    - kind: ThinItalic
      font: JetBrains Mono NL Thin Italic Nerd Font Complete Mono
  notify:
    - Rebuild local font cache
