---
# on archlinux install the ttf-meslo-nerd-font-powerlevel10k package
# https://aur.archlinux.org/packages/ttf-meslo-nerd-font-powerlevel10k/
# and the nerd-fonts-jetbrains-mono package
# https://aur.archlinux.org/packages/nerd-fonts-jetbrains-mono/

- name: Creating local fonts directory
  when: ansible_os_family == "Debian"
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.local/share/fonts"
    state: directory

- name: Creating Nerd Fonts directory
  when: ansible_os_family == "Debian"
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.local/share/fonts/Bitstream/\
      TrueType/{{ item }}"
    state: directory
  loop:
    - JetBrains Mono NF
    - MesloLGS NF

- name: Downloading MesloLGS Nerd Font (on macOS)
  when: ansible_os_family == "Darwin"
  ansible.builtin.get_url:
    dest: "{{ ansible_user_dir }}/Library/Fonts/{{ item }}.ttf"
    group: "{{ whoami_group }}"
    mode: "0664"
    owner: "{{ whoami }}"
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/\
      {{ item | urlencode }}.ttf"
  loop:
    - MesloLGS NF Bold
    - MesloLGS NF Bold Italic
    - MesloLGS NF Italic
    - MesloLGS NF Regular

- name: Downloading MesloLGS Nerd Font (on Debian)
  when: ansible_os_family == "Debian"
  ansible.builtin.get_url:
    dest: "{{ ansible_user_dir }}/.local/share/fonts/Bitstream/\
      TrueType/MesloLGS NF/{{ item | replace(' ', '_') }}.ttf"
    group: "{{ whoami_group }}"
    mode: "0644"
    owner: "{{ whoami }}"
    url: "https://github.com/romkatv/powerlevel10k-media/raw/\
      master/{{ item | urlencode }}.ttf"
  loop:
    - MesloLGS NF Bold
    - MesloLGS NF Bold Italic
    - MesloLGS NF Italic
    - MesloLGS NF Regular
  notify:
    - Rebuild local font cache

- name: Downloading Jetbrains Nerd Font (on Debian)
  when: ansible_os_family == "Debian"
  ansible.builtin.get_url:
    dest: "{{ ansible_user_dir }}/.local/share/fonts/Bitstream/\
      TrueType/JetBrains Mono NF/{{ item.font | replace(' ', '_') }}.ttf"
    group: "{{ whoami_group }}"
    mode: "0644"
    owner: "{{ whoami }}"
    url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/\
      JetBrainsMono/NoLigatures/{{ item.kind }}/complete/\
      {{ item.font | urlencode }}.ttf"
  loop:
    - kind: Bold
      font: JetBrains Mono NL Bold Nerd Font Complete Mono
    - kind: BoldItalic
      font: JetBrains Mono NL Bold Italic Nerd Font Complete Mono
    - kind: ExtraBold
      font: JetBrains Mono NL ExtraBold Nerd Font Complete Mono
    - kind: ExtraBoldItalic
      font: JetBrains Mono NL ExtraBold Italic Nerd Font Complete Mono
    - kind: ExtraLight
      font: JetBrains Mono NL ExtraLight Nerd Font Complete Mono
    - kind: ExtraLightItalic
      font: JetBrains Mono NL ExtraLight Italic Nerd Font Complete Mono
    - kind: Italic
      font: JetBrains Mono NL Italic Nerd Font Complete Mono
    - kind: Light
      font: JetBrains Mono NL Light Nerd Font Complete Mono
    - kind: LightItalic
      font: JetBrains Mono NL Light Italic Nerd Font Complete Mono
    - kind: Medium
      font: JetBrains Mono NL Medium Nerd Font Complete Mono
    - kind: MediumItalic
      font: JetBrains Mono NL Medium Italic Nerd Font Complete Mono
    - kind: Regular
      font: JetBrains Mono NL Regular Nerd Font Complete Mono
    - kind: SemiBold
      font: JetBrains Mono NL SemiBold Nerd Font Complete Mono
    - kind: SemiBoldItalic
      font: JetBrains Mono NL SemiBold Italic Nerd Font Complete Mono
    - kind: Thin
      font: JetBrains Mono NL Thin Nerd Font Complete Mono
    - kind: ThinItalic
      font: JetBrains Mono NL Thin Italic Nerd Font Complete Mono
  notify:
    - Rebuild local font cache
