---
# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: symlink one liner functions
  file:
    dest: "{{ ansible_user_dir }}/.zsh/oneliners.zsh"
    src: "{{ playbook_dir }}/roles/zsh/files/oneliners.zsh"
    state: link

- name: ensure functions directory
  file:
    path: "{{ ansible_user_dir }}/.zsh/_functions"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0755
    state: directory

- name: clone gist function alias repos
  git:
    dest: "{{ ansible_user_dir }}/.zsh/_functions/{{ item.alias }}"
    repo: "{{ item.repo }}"
    version: HEAD
  loop: "{{ gist_function_aliases }}"
