---
# on archlinux we install the `grml-zsh-config` package
- name: ensure grml-zsh-config download directory
  when: ansible_os_family == "Darwin"
  file:
    path: "{{ ansible_user_dir }}/.config/zsh"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0755
    state: directory

- name: download grml-zsh-config
  when: ansible_os_family == "Darwin"
  git:
    dest: "{{ ansible_user_dir }}/.config/zsh/grml"
    repo: https://github.com/grml/grml-etc-core.git
    version: v0.17.4

# i'd prefer this to be a symlink but then we miss out on ansible being able
# to process it, run if/else, and drop in encrypted variables...
# - name: install zshrc
#   template:
#     dest: "{{ ansible_user_dir }}/.zshrc"
#     owner: "{{ whoami }}"
#     group: "{{ whoami_group }}"
#     mode: 0600
#     src: zshrc.j2
