---
- name: Creating zsh configuration directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.zsh"
    state: directory

- name: Installing grml-zsh-config
  ansible.builtin.git:
    dest: "{{ ansible_user_dir }}/.zsh/grml"
    repo: https://github.com/grml/grml-etc-core.git
    version: v0.19.15

- name: Installing zsh-abbr
  ansible.builtin.git:
    dest: "{{ ansible_user_dir }}/.zsh/abbr"
    repo: https://github.com/olets/zsh-abbr.git
    version: v6.2.1

- name: Installing zsh suggestions abbr-strategy
  ansible.builtin.git:
    dest: "{{ ansible_user_dir }}/.zsh/autosuggestions-abbr"
    repo: >-
      https://github.com/olets/zsh-autosuggestions-abbreviations-strategy.git
    version: v1.1.1

- name: Installing powerlevel10k
  ansible.builtin.git:
    dest: "{{ ansible_user_dir }}/.zsh/powerlevel10k"
    repo: https://github.com/romkatv/powerlevel10k.git
    version: v1.20.0

- name: Installing oh-my-zsh
  ansible.builtin.git:
    dest: "{{ ansible_user_dir }}/.zsh/ohmyzsh"
    repo: https://github.com/ohmyzsh/ohmyzsh.git

# i'd prefer this to be a symlink but then we miss out on ansible being able
# to process it, run if/else, and drop in encrypted variables...
- name: Copying zsh configuration
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.zshrc"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: zshrc.j2

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking p10k configuration
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.p10k.zsh"
    src: "{{ playbook_dir }}/roles/zsh/files/p10k.zsh"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking dummy file for the "unlockmf" function
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.zsh/36FDA306.asc"
    src: "{{ playbook_dir }}/roles/zsh/files/36FDA306.asc"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking the dummy file for the "unlockw" function
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.zsh/4DA7BCBA.asc"
    src: "{{ playbook_dir }}/roles/zsh/files/4DA7BCBA.asc"
    state: link

- name: Configuring gist aliases
  ansible.builtin.import_tasks: functions.yml

- name: Configuring other shell-related tools
  ansible.builtin.import_tasks: other.yml
