---
urlwatch_config_basepath:
  Darwin: "{{ ansible_user_dir }}/Library/Application Support/urlwatch"
  Debian: "{{ ansible_user_dir }}/.config/urlwatch"
  Archlinux: "{{ ansible_user_dir }}/.config/urlwatch"

urlwatch_github_releases:
  - actions/checkout
  - actions/create-release
  - actions/setup-ruby
  - ansible/ansible-lint-action
  - docker/login-action
  - docker/build-push-action
  - docker/setup-buildx-action
  - peter-evans/dockerhub-description

urlwatch_github_releases_complex:
  - ruby/setup-ruby

  # aur packages
  - vrana/adminer
  - mikefarah/yq
  - houmain/keymapper
  - IBM-Cloud/redli
  - hayorov/helm-gcs
  - hypnoglow/helm-s3
  - jkroepke/helm-secrets
  - newrelic/newrelic-cli
  - FairwindsOps/pluto

urlwatch_github_helm_releases:
  - bitnami/charts/master/bitnami/kube-state-metrics
  - bitnami/charts/master/bitnami/metrics-server
  - kubernetes/ingress-nginx/master/charts/ingress-nginx
  - newrelic/helm-charts/master/charts/newrelic-infrastructure
  - newrelic/helm-charts/master/charts/newrelic-logging

urlwatch_rubygems:
  - bankrupt
  - ruolo

  # aur packages
  - airbrussh
  - benchmark-ips
  - buftok
  - bump
  - capistrano
  - cliver
  - coderay
  - digest-crc
  - docile
  - exifr
  - formatador
  - fuubar
  - git
  - guard-compat
  - guard-rspec
  - haml
  - hashie
  - http-accept
  - ice_nine
  - image_size
  - jaro_winkler
  - librarianp
  - logger-application
  - mechanize
  - memoizable
  - mimemagic
  - minitest-reporters
  - mini_magick
  - mono_logger
  - net-http-digest_auth
  - netrc
  - notiffany
  - oedipus_lex
  - oj
  - parallel
  - parser
  - powerpack
  - pry
  - racc
  - rchardet
  - regexp_parser
  - regexp_property_values
  - rest-client
  - rspec-pending_for
  - rspectacular
  - rubocop
  - rubocop-ast
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - ruby-progressbar
  - rubygems-tasks
  - ruby_engine
  - ruby_version
  - set
  - shellany
  - slim
  - sorted_set
  - sshkit
  - test-queue
  - timecop
  - uber

urlwatch_npm_packages:
  - autoprefixer
  - clean-css-cli
  - express-generator
  - mjml
  - postcss
  - postcss-cli
  - pug-cli
