---
urlwatch_config_basepath:
  Darwin: "{{ ansible_user_dir }}/Library/Application Support/urlwatch"
  Debian: "{{ ansible_user_dir }}/.config/urlwatch"
  Archlinux: "{{ ansible_user_dir }}/.config/urlwatch"

urlwatch_github_releases:
  - actions/checkout
  - actions/create-release
  - actions/setup-ruby
  - ansible/ansible-lint-action
  - docker/login-action
  - docker/build-push-action
  - docker/setup-buildx-action
  - peter-evans/dockerhub-description
  - ruby/setup-ruby

urlwatch_github_helm_releases:
  - bitnami/charts/master/bitnami/kube-state-metrics
  - bitnami/charts/master/bitnami/metrics-server
  - kubernetes/ingress-nginx/master/charts/ingress-nginx
  - newrelic/helm-charts/master/charts/newrelic-infrastructure
  - newrelic/helm-charts/master/charts/newrelic-logging

urlwatch_rubygems:
  - bankrupt
  - ruolo

  # aur packages
  - airbrussh
  - bump
  - cliver
  - coderay
  - fast_gettext
  - gettext-setup
  - git
  - jaro_winkler
  - librarianp
  - mimemagic
  - minitar
  - mini_magick
  - netrc
  - oj
  - parallel
  - parser
  - pry
  - racc
  - rchardet
  - regexp_parser
  - rexml
  - rubocop
  - rubocop-ast
  - ruby-progressbar
  - sshkit
