---
urlwatch_config_basepath:
  Darwin: "{{ ansible_user_dir }}/Library/Application Support/urlwatch"
  Debian: "{{ ansible_user_dir }}/.config/urlwatch"
  Archlinux: "{{ ansible_user_dir }}/.config/urlwatch"

urlwatch_github_releases:
  - actions/checkout
  - actions/create-release
  - ansible/ansible-lint-action
  - docker/login-action
  - docker/build-push-action
  - docker/setup-buildx-action
  - ansible-collections/community.general
  - ansible-collections/ansible.posix

urlwatch_github_releases_complex:
  # aur packages
  - vrana/adminer
  - mikefarah/yq
  - houmain/keymapper
  - IBM-Cloud/redli
  - hayorov/helm-gcs
  - hypnoglow/helm-s3
  - jkroepke/helm-secrets
  - newrelic/newrelic-cli
  - FairwindsOps/pluto
  - kewlfft/ansible-aur
  - tj/n
  - spf13/cobra-cli
  - asciinema/agg

  # other
  - ansible-collections/kubernetes.core
  - cert-manager/cert-manager
  - charite/jannovar
  - kyleconroy/sqlc

urlwatch_github_helm_releases:
  - bitnami/charts/master/bitnami/common
  - bitnami/charts/master/bitnami/kube-state-metrics
  - bitnami/charts/master/bitnami/metrics-server
  - kubernetes-sigs/metrics-server/master/charts/metrics-server
  - bitnami/charts/master/bitnami/redis
  - kubernetes/ingress-nginx/master/charts/ingress-nginx
  - newrelic/helm-charts/master/charts/newrelic-infrastructure
  - newrelic/helm-charts/master/charts/newrelic-logging
  - prometheus-community/helm-charts/main/charts/kube-state-metrics
  - stakater/Reloader/master/deployments/kubernetes/chart/reloader

urlwatch_rubygems:
  - bankrupt
  - ruolo

  # aur packages
  - airbrussh
  - buftok
  - capistrano
  - cliver
  - declarative
  - digest-crc
  - docile
  - emoji_regex
  - exifr
  - faker
  - fuubar
  - git
  - guard-compat
  - guard-rspec
  - hashie
  - http-accept
  - image_size
  - jaro_winkler
  - librarianp
  - logger-application
  - mechanize
  - memoizable
  - mimemagic
  - minitest-reporters
  - mini_magick
  - mono_logger
  - net-http-digest_auth
  - notiffany
  - oedipus_lex
  - oj
  - parser
  - powerpack
  - rchardet
  - rest-client
  - rspec-pending_for
  - rspectacular
  - rubocop
  - rubocop-ast
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - ruby_engine
  - ruby_version
  - sshkit
  - test-queue
  - uber

urlwatch_npm_packages:
  - '@lhci/cli'
  - autoprefixer
  - clean-css-cli
  - express-generator
  - mjml
  - postcss
  - postcss-cli
  - pug-cli
