---
urlwatch_config_basepath:
  Archlinux: "{{ ansible_user_dir }}/.config/urlwatch"
  Darwin: "{{ ansible_user_dir }}/Library/Application Support/urlwatch"
  Debian: "{{ ansible_user_dir }}/.config/urlwatch"

urlwatch_github_releases:
  - ansible-collections/ansible.posix
  - ansible-collections/community.general

urlwatch_github_releases_complex:
  # aur packages
  - 1Password/connect-sdk-python
  - FairwindsOps/pluto
  - IBM-Cloud/redli
  - asciinema/agg
  - hayorov/helm-gcs
  - houmain/keymapper
  - hypnoglow/helm-s3
  - jkroepke/helm-secrets
  - kewlfft/ansible-aur
  - leighmcculloch/vangen
  - mikefarah/yq
  - newrelic/newrelic-cli
  - spf13/cobra-cli
  - tj/n
  - vrana/adminer

  # other
  - Bash-it/bash-it
  - ansible-collections/kubernetes.core
  - cert-manager/cert-manager
  - charite/jannovar
  - kyleconroy/sqlc

urlwatch_github_helm_releases:
  - bitnami/charts/master/bitnami/common
  - bitnami/charts/master/bitnami/kube-state-metrics
  - bitnami/charts/master/bitnami/metrics-server
  - bitnami/charts/master/bitnami/redis
  - kubernetes-sigs/metrics-server/master/charts/metrics-server
  - kubernetes/ingress-nginx/master/charts/ingress-nginx
  - newrelic/helm-charts/master/charts/newrelic-infrastructure
  - newrelic/helm-charts/master/charts/newrelic-logging
  - prometheus-community/helm-charts/main/charts/kube-state-metrics
  - stakater/Reloader/master/deployments/kubernetes/chart/reloader

urlwatch_rubygems:
  - bankrupt
  - ruolo

  # aur packages
  - abstract_type
  - adamantium
  - airbrussh
  - buftok
  - capistrano
  - cliver
  - concord
  - declarative
  - digest-crc
  - docile
  - emoji_regex
  - equalizer
  - exifr
  - faker
  - fuubar
  - git
  - guard-compat
  - guard-rspec
  - hashie
  - http-accept
  - image_size
  - jaro_winkler
  - librarianp
  - logger-application
  - mechanize
  - memoizable
  - mimemagic
  - mini_magick
  - minitest-reporters
  - mono_logger
  - net-http-digest_auth
  - notiffany
  - oedipus_lex
  - oj
  - parser
  - powerpack
  - rchardet
  - rest-client
  - rspec-pending_for
  - rspectacular
  - rubocop
  - rubocop-ast
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - ruby_engine
  - ruby_version
  - sshkit
  - test-queue
  - uber
  - yardstick

urlwatch_npm_packages:
  - '@lhci/cli'
  - autoprefixer
  - clean-css-cli
  - express-generator
  - mjml
  - postcss
  - postcss-cli
  - pug-cli
