---
- name: Ensure aws directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.aws"
    state: directory

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Link aws config
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.aws/config"
    src: "{{ playbook_dir }}/roles/aws/files/config"
    state: link

- name: Install aws credentials
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.aws/credentials"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: credentials.j2
