---
- name: Enable keyboard layouts
  community.general.dconf:
    key: /org/gnome/desktop/input-sources/sources
    value: "[('xkb', 'us'), ('xkb', 'it')]"

- name: Get the ID of the gnome terminal profile
  ansible.builtin.shell: >-
    set -e -o pipefail;
    dconf list /org/gnome/terminal/legacy/profiles:/ | head -n1 |
      awk -F: '{print $2}' | awk -F/ '{print $1}'
  register: gnome_terminal_profile
  changed_when: false
  args:
    executable: /bin/bash

- name: Configure gnome terminal
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:\
      {{ gnome_terminal_profile.stdout }}/{{ item.key }}"
    value: "{{ item.value | string }}"
  loop:
    - key: visible-name
      value: "'mario'"
    - key: use-system-font
      value: "false"
    - key: font
      value: "'JetBrainsMono Nerd Font Mono 12'"
    - key: use-theme-colors
      value: "false"
    - key: audible-bell
      value: "false"
    - key: foreground-color
      value: "'rgb(255,255,255)'"
    - key: background-color
      value: "'rgb(0,0,0)'"
    - key: palette
      value: >-
        ['rgb(0,0,0)', 'rgb(170,0,0)', 'rgb(0,170,0)', 'rgb(170,85,0)',
        'rgb(0,0,170)', 'rgb(170,0,170)', 'rgb(0,170,170)', 'rgb(170,170,170)',
        'rgb(85,85,85)', 'rgb(255,85,85)', 'rgb(85,255,85)', 'rgb(255,255,85)',
        'rgb(85,85,255)', 'rgb(255,85,255)', 'rgb(85,255,255)',
        'rgb(255,255,255)']
    - key: bold-is-bright
      value: "true"

- name: Configure screen lock
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: /org/gnome/desktop/screensaver/lock-delay
      value: uint32 0
    - key: /org/gnome/desktop/session/idle-delay
      value: uint32 600
    - key: /org/gnome/desktop/notifications/show-in-lock-screen
      value: "false"

- name: Turn off natural scrolling
  community.general.dconf:
    key: /org/gnome/desktop/peripherals/touchpad/natural-scroll
    value: "false"

- name: Never prompt or start programs on media insertion
  community.general.dconf:
    key: /org/gnome/desktop/media-handling/autorun-never
    value: "true"

- name: Configure top bar time
  community.general.dconf:
    key: /org/gnome/desktop/interface/{{ item }}
    value: "true"
  loop:
    - clock-show-seconds
    - clock-show-weekday

- name: Configure gnome shell extensions
  when: ansible_os_family == 'Archlinux'
  community.general.dconf:
    key: /org/gnome/shell/enabled-extensions
    value: "[{{ gnome_extensions | join(', ') }}]"

- name: Configure gnome shell dash-to-dock
  when: ansible_os_family == 'Archlinux'
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/{{ item.key }}
    value: "{{ item.value }}"
  loop:
    - key: dock-position
      value: "'LEFT'"
    - key: extend-height
      value: "true"
    - key: custom-theme-shrink
      value: "true"

- name: Configure systemd manager extension
  when: ansible_os_family == 'Archlinux'
  community.general.dconf:
    key: /org/gnome/shell/extensions/systemd-manager/{{ item.key }}
    value: "{{ item.value }}"
  loop:
    - key: show-add
      value: "false"
    - key: command-method
      value: "'systemctl'"

- name: Set systemd service manager services
  when:
    - ansible_os_family == 'Archlinux'
  community.general.dconf:
    key: /org/gnome/shell/extensions/systemd-manager/systemd
    value: >-
      ['{"name":"Docker","service":"docker.service","type":"system"}',
      '{"name":"libvirtd","service":"libvirtd.service","type":"system"}']

- name: Configure dock apps
  when: ansible_os_family == 'Archlinux' and mtype == 'work'
  community.general.dconf:
    key: /org/gnome/shell/favorite-apps
    value: "[{{ gnome_work_dock | join(', ') }}]"

- name: Configure dock apps
  when: ansible_os_family == 'Archlinux' and mtype == 'personal'
  community.general.dconf:
    key: /org/gnome/shell/favorite-apps
    value: "[{{ gnome_personal_dock | join(', ') }}]"

- name: Configure arc menu
  when: ansible_os_family == 'Archlinux'
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: /org/gnome/shell/extensions/arcmenu/menu-layout
      value: "'Default'"
    - key: /org/gnome/shell/extensions/arcmenu/show-external-devices
      value: "false"
    - key: /org/gnome/shell/extensions/arcmenu/pinned-app-list
      value: "@as []"
    - key: /org/gnome/shell/extensions/arcmenu/default-menu-view
      value: "'Frequent_Apps'"
    - key: /org/gnome/shell/extensions/arcmenu/searchbar-default-bottom-location
      value: "'Top'"
    - key: /org/gnome/shell/extensions/arcmenu/distro-icon
      value: "6" # archlinux
