---
- name: Copying `.gitconfig`
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gitconfig"
    group: "{{ whoami_group }}"
    mode: "0644"
    owner: "{{ whoami }}"
    src: gitconfig.j2

- name: Creating git configuration directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.config/git"
    state: directory

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking global "gitignore"
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/git/gitignore"
    src: "{{ playbook_dir }}/roles/git/files/gitignore_global"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking custom git configuration
  when: mtype == 'work'
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/git/personal"
    src: "{{ playbook_dir }}/roles/git/files/gitconfig_personal"
    state: link
