---
# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Link gitignore_global
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.gitignore_global"
    src: "{{ playbook_dir }}/roles/git/files/gitignore_global"
    state: link

- name: Install user global git config
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gitconfig"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: "0644"
    src: gitconfig.j2

- name: Create custom gitconfig directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/git"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: "0755"
    state: directory

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Install custom gitconfig
  when: mtype == 'work'
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/git/personal"
    src: "{{ playbook_dir }}/roles/git/files/gitconfig_personal"
    state: link
