---
- name: ensure hexchat directory
  file:
    path: "{{ ansible_user_dir }}/.config/hexchat"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0700
    state: directory

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: symlink hexchat config file
  file:
    dest: "{{ ansible_user_dir }}/.config/hexchat.conf"
    src: "{{ playbook_dir }}/roles/hexchat/files/hexchat.conf"
    state: link
    force: true

- name: copy hexchat server list
  template:
    dest: "{{ ansible_user_dir }}/.config/servlist.conf"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0600
    src: servlist.conf.j2
