---
- name: Ensure hexchat directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0700"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.config/hexchat"
    state: directory

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Symlink hexchat config file
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/hexchat/hexchat.conf"
    force: true
    src: "{{ playbook_dir }}/roles/hexchat/files/hexchat.conf"
    state: link

- name: Copy hexchat server list
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.config/hexchat/servlist.conf"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: servlist.conf.j2
