set nocompatible
set encoding=utf-8
set fileencoding=utf-8
scriptencoding utf-8

" make searching better
set ignorecase
set smartcase

" show line numbers
set relativenumber

" turn on syntax highlighting
" https://stackoverflow.com/a/33380495
if !exists("g:syntax_on")
  syntax enable
endif

" turn on filetype detection
" https://vi.stackexchange.com/a/10125
" https://github.com/tpope/vim-sensible
if has('autocmd')
  filetype plugin indent on
endif

" set backspace to work like we expect
" https://vi.stackexchange.com/a/2163
set backspace=indent,eol,start

" automatically indent
set autoindent

" make autocomplete better
" https://medium.com/usevim/set-complete-e76b9f196f0f
set complete-=i

" set colors
" colorscheme bubblegum-256-dark
" let g:airline_theme='bubblegum'
colorscheme jellybeans
let g:airline_theme='jellybeans'

" increase frequency of gitgutter updates
set updatetime=100

" reload files that are changed on disk
set autoread

" increase history size
" https://github.com/tpope/vim-sensible
if &history < 1000
  set history=1000
endif
if &tabpagemax < 50
  set tabpagemax=50
endif

" enable spell check on markdown and git commit messages
autocmd FileType gitcommit setlocal spell spelllang=en
autocmd FileType markdown setlocal spell spelllang=en

" use foldmethod=indent but start with all folds open
" then set the fdm to manual to allow custom folds as needed
" https://stackoverflow.com/a/23672376
" https://vim.fandom.com/wiki/Folding#Indent_folding_with_manual_folds
augroup vimrc
  " set foldmethod=syntax
  autocmd BufReadPre * setlocal foldmethod=syntax
  autocmd BufRead * silent! :%foldopen!
  au BufWinEnter * if &fdm == 'syntax' | setlocal foldmethod=manual | endif
augroup END

" enable syntax highlighting in markdown code blocks
" https://github.com/tpope/vim-markdown
let g:markdown_fenced_languages = ['ruby', 'shell=sh']

set colorcolumn=80

if executable("ag")
  " https://stackoverflow.com/a/18601066
  let g:ctrlp_user_command = 'ag %s -l --nocolor --hidden --path-to-ignore ~/.vim/.ignore -g ""'
else
  " https://github.com/kien/ctrlp.vim/issues/58#issuecomment-42743551
  let g:ctrlp_custom_ignore = '\v[\/](node_modules|vendor\/bundle)|(\.(git))$'
  let g:ctrlp_show_hidden = 1
endif

" https://stackoverflow.com/a/60655244
let g:NERDTreeShowHidden = 1
let g:NERDTreeIgnore = ['\.git$']

let g:gutentags_cache_dir = $HOME . '/.cache/gutentags'
