---
# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: link makepkg config
  file:
    dest: "{{ ansible_user_dir }}/.makepkg.conf"
    src: "{{ playbook_dir }}/roles/arch/files/makepkg.conf"
    state: link
