---
- name: Creating makepkg configuration directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.config/pacman"
    state: directory

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking makepkg configuration
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/pacman/makepkg.conf"
    src: "{{ playbook_dir }}/roles/arch/files/makepkg.conf"
    state: link

- name: Creating packaging chroot directories
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: directory
  loop:
    - .local
    - .local/var
    - .local/var/chroot
    - .local/var/smchroot
