---
- name: Ensure terraform configuration directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.terraform.d"
    state: directory

- name: Install terraform cloud credentials
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.terraform.d/credentials.tfrc.json"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: credentials.tfrc.json.j2
