---
- name: Creating ghostty configuration directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ghostty_config_path[ansible_system] }}"
    state: directory

- name: Linking starship configuration
  ansible.builtin.template:
    dest: "{{ ghostty_config_path[ansible_system] }}/config"
    group: "{{ whoami_group }}"
    mode: "0644"
    owner: "{{ whoami }}"
    src: config.j2
