---
# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: link tmux conf
  file:
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    src: "{{ playbook_dir }}/roles/tmux/files/tmux.conf"
    state: link

- name: ensure extra tmux directory
  file:
    path: "{{ ansible_user_dir }}/.tmux"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0755
    state: directory

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: link the os configure script
  file:
    dest: "{{ ansible_user_dir }}/.tmux/os.bash"
    src: "{{ playbook_dir }}/roles/tmux/files/os.bash"
    state: link
