---
- name: Creating tmux configuration directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.config/tmux"
    state: directory

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking tmux configuration
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/tmux/tmux.conf"
    src: "{{ playbook_dir }}/roles/tmux/files/tmux.conf"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking tmux OS icon script
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/tmux/os.bash"
    src: "{{ playbook_dir }}/roles/tmux/files/os.bash"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking tmux UTC date script
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/tmux/date.sh"
    src: "{{ playbook_dir }}/roles/tmux/files/date.sh"
    state: link
