---
- name: Creating screen configuration directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.config/screen"
    state: directory

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking screen hostname script
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/screen/hn.sh"
    src: "{{ playbook_dir }}/roles/screen/files/hn.sh"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking screen session name script
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/screen/sty.sh"
    src: "{{ playbook_dir }}/roles/screen/files/sty.sh"
    state: link

- name: Copying screen configuration
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.screenrc"
    group: "{{ whoami_group }}"
    mode: "0644"
    owner: "{{ whoami }}"
    src: screenrc.j2
