---
vim_plugins_dirs:
  - "{{ ansible_user_dir }}/.vim/"
  - "{{ ansible_user_dir }}/.vim/pack"
  - "{{ ansible_user_dir }}/.vim/pack/local"
  - "{{ ansible_user_dir }}/.vim/pack/local/opt"
  - "{{ ansible_user_dir }}/.vim/pack/local/start"
  - "{{ ansible_user_dir }}/.vim/syntax"

vim_neovim_plugins_dirs:
  - "{{ ansible_user_dir }}/.local"
  - "{{ ansible_user_dir }}/.local/share"
  - "{{ ansible_user_dir }}/.local/share/nvim"
  - "{{ ansible_user_dir }}/.local/share/nvim/site"
  - "{{ ansible_user_dir }}/.local/share/nvim/site/pack"
  - "{{ ansible_user_dir }}/.local/share/nvim/site/pack/local"
  - "{{ ansible_user_dir }}/.local/share/nvim/site/pack/local/start"

vim_neovim_config_dirs:
  - "{{ ansible_user_dir }}/.config"
  - "{{ ansible_user_dir }}/.config/nvim"
  - "{{ ansible_user_dir }}/.config/nvim/lua"

vim_plugins:
  - name: airline
    repo: https://github.com/vim-airline/vim-airline.git
  - name: airline-themes
    repo: https://github.com/vim-airline/vim-airline-themes.git
  - name: ale
    repo: https://github.com/dense-analysis/ale.git
  - name: ansible
    repo: https://github.com/pearofducks/ansible-vim.git
  - name: brewfile
    repo: https://github.com/bfontaine/Brewfile.vim.git
  - name: characterize
    repo: https://github.com/tpope/vim-characterize.git
  - name: commentary
    repo: https://github.com/tpope/vim-commentary.git
  - name: ctrlp
    repo: https://github.com/ctrlpvim/ctrlp.vim.git
  - name: devicons
    repo: https://github.com/ryanoasis/vim-devicons.git
  - name: editorconfig
    repo: https://github.com/editorconfig/editorconfig-vim.git
  - name: fugitive
    repo: https://github.com/tpope/vim-fugitive.git
  - name: gitgutter
    repo: https://github.com/airblade/vim-gitgutter.git
  - name: gitlens
    repo: https://github.com/Eliot00/git-lens.vim.git
  - name: gutentags
    repo: https://github.com/ludovicchabant/vim-gutentags.git
  # - name: helm
  #   repo: https://github.com/towolf/vim-helm.git
  - name: just
    repo: https://github.com/NoahTheDuke/vim-just.git
  - name: mjml
    repo: https://github.com/amadeus/vim-mjml.git
  # - name: indentline
  #   repo: https://github.com/Yggdroot/indentLine.git
  - name: narrow
    repo: https://github.com/chrisbra/NrrwRgn.git
  - name: nerdtree
    repo: https://github.com/preservim/nerdtree.git
  - name: nerdtree-git
    repo: https://github.com/Xuyuanp/nerdtree-git-plugin.git
  - name: nginx
    repo: https://github.com/chr4/nginx.vim.git
  - name: pencil
    repo: https://github.com/preservim/vim-pencil.git
  - name: pug
    repo: https://github.com/digitaltoad/vim-pug.git
  - name: slim
    repo: https://github.com/slim-template/vim-slim.git
  - name: svelte
    repo: https://github.com/leafOfTree/vim-svelte-plugin.git
  - name: systemd
    repo: https://github.com/wgwoods/vim-systemd-syntax.git
  - name: tagbar
    repo: https://github.com/preservim/tagbar.git
  - name: terraform
    repo: https://github.com/hashivim/vim-terraform.git
  - name: toml
    repo: https://github.com/cespare/vim-toml.git
  - name: typescript
    repo: https://github.com/leafgarland/typescript-vim.git

  - name: bubblegum
    repo: https://github.com/baskerville/bubblegum.git
  - name: jellybeans
    repo: https://github.com/nanotech/jellybeans.vim.git

vim_syntax_files:
  - name: gohtmltmpl
    url: https://github.com/fatih/vim-go/raw/master/syntax/gohtmltmpl.vim
  - name: gotexttmpl
    url: https://github.com/fatih/vim-go/raw/master/syntax/gotexttmpl.vim

vim_neovim_plugins:
  - name: gitlens
    repo: https://github.com/APZelos/blamer.nvim.git
  - name: treesitter
    repo: https://github.com/nvim-treesitter/nvim-treesitter.git
