---
- name: Creating vim plugin directories
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ item }}"
    state: directory
  loop: "{{ vim_plugins_dirs }}"

- name: Installing vim plugins
  ansible.builtin.git:
    dest: "{{ ansible_user_dir }}/.vim/pack/local/start/{{ item.name }}"
    repo: "{{ item.repo }}"
    version: HEAD
  loop: "{{ vim_plugins }}"

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking the vim configuration file
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.vimrc"
    src: "{{ playbook_dir }}/roles/vim/files/vimrc"
    state: link

- name: Linking silver searcher ignore file
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.vim/.ignore"
    src: "{{ playbook_dir }}/roles/vim/files/ignore"
    state: link

- name: Creating neovim configuration directories
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ item }}"
    state: directory
  loop: "{{ neovim_config_dirs }}"

- name: Creating neovim plugin directories
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ item }}"
    state: directory
  loop: "{{ neovim_plugins_dirs }}"

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking neovim configuration file
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/nvim/init.vim"
    src: "{{ playbook_dir }}/roles/vim/files/init.vim"
    state: link

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Linking neovim lua configuration file
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/nvim/lua/init.lua"
    src: "{{ playbook_dir }}/roles/vim/files/init.lua"
    state: link

- name: Installing neovim plugins
  ansible.builtin.git:
    dest: "{{ ansible_user_dir }}/.local/share/nvim/site/pack/local/\
      start/{{ item.name }}"
    repo: "{{ item.repo }}"
    version: HEAD
  loop: "{{ neovim_plugins }}"
