---
- name: ensure urlwatch directory
  file:
    path: "{{ ansible_user_dir }}/.config/urlwatch"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0755
    state: directory

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: link the urlwatch configuration
  file:
    dest: "{{ urlwatch_config_basepath }/urlwatch.yaml"
    src: "{{ playbook_dir }}/roles/urlwatch/files/urlwatch.yaml"
    state: link

- name: install urlwatch list
  template:
    dest: "{{ urlwatch_config_basepath }}/urls.yaml"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0644
    src: urls.yaml.j2
