---
- name: Ensure urlwatch directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ urlwatch_config_basepath[ansible_os_family] }}"
    state: directory

# this is ok, because boostrap.bash calls dotfiles.yml as the playbook
- name: Link the urlwatch configuration
  ansible.builtin.file:
    dest: "{{ urlwatch_config_basepath[ansible_os_family] }}/urlwatch.yaml"
    src: "{{ playbook_dir }}/roles/urlwatch/files/urlwatch.yaml"
    state: link

- name: Install urlwatch list
  ansible.builtin.template:
    dest: "{{ urlwatch_config_basepath[ansible_os_family] }}/urls.yaml"
    group: "{{ whoami_group }}"
    mode: "0644"
    owner: "{{ whoami }}"
    src: urls.yaml.j2
