---
- name: Creating Rubygems configuration directory
  ansible.builtin.file:
    group: "{{ whoami_group }}"
    mode: "0755"
    owner: "{{ whoami }}"
    path: "{{ ansible_user_dir }}/.gem"
    state: directory

- name: Copying Rubygems credentials
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gem/credentials"
    group: "{{ whoami_group }}"
    mode: "0600"
    owner: "{{ whoami }}"
    src: credentials.j2
