---
- name: ensure .gem directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.gem"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0755
    state: directory

- name: install gem credentials
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gem/credentials"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0600
    src: credentials.j2
