---
name: Lint
on: push # yamllint disable-line rule:truthy

jobs:
  main:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mfinelli/setup-shfmt@v2
      - run: npm install -g prettier
      - run: |
          shellcheck --version
          shellcheck go vault wvault
          find . -name '*.bash' | xargs shellcheck
          find . -name '*.sh' | xargs shellcheck
      - run: |
          shfmt --version
          shfmt -s -i 2 -ci -sr -d go vault wvault
          find . -name '*.bash' | xargs shfmt -s -i 2 -ci -sr -d
          find . -name '*.sh' | xargs shfmt -s -i 2 -ci -sr -d
      - run: find . -name '*.yaml' -o -name '*.yml' | xargs prettier -c
      - uses: ansible-community/ansible-lint-action@v6
        with:
          path: dotfiles.yml
