---
name: Lint
on: push

jobs:
  main:
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ansible-community/ansible-lint-action@v6
        with:
          path: dotfiles.yml
